version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo-app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/todo
    command: ["bun", "start"]

volumes:
  todo-data:
