version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DATABASE_URL: postgres://admin:secret@db:5432/todo
    ports:
      - "3000:3000"
    depends_on:
      - db
